### ISSUE TITLE
Question on how to make this script work

### ISSUE THREAD

**Issue by blc1996** [jenting/secure-metrics-server#1]
Hi. I'm trying to securely deploy metrics-server using your script.

I have two questions maybe you could help answer.

1) How is the created secret `metrics-server-cert` related to metrics-server?

2) What exactly is `pki/ca.crt` passed to caBundle 

Thank you!

**Comment by jenting** [comment]
> Hi. I'm trying to securely deploy metrics-server using your script.
> 
> I have two questions maybe you could help answer.
> 

Thank you for interesting in this project.

> 1. How is the created secret `metrics-server-cert` related to metrics-server?

I think I missed how to configure the metrics-server Deployment to use the created secret `metrics-server-cert`, I'll update it later.

> 2. What exactly is `pki/ca.crt` passed to caBundle

It's a CA certificate file that is the signer of kube-apiserver.

> 
> Thank you!

**Comment by blc1996** [comment]
Hi @jenting , thanks for the answer, I really appreciate it.

**Comment by jenting** [comment]
> Hi @jenting , thanks for the answer, I really appreciate it.

@blc1996, the commit has addressed your question https://github.com/jenting/secure-metrics-server/commit/7e1d085b7d69fb72fe07355cc54a56c377c95033, hope it helps you :rocket:
